mod_id=dummyplayers
mod_version=26.2
release_type=release
minecraft_version=26.2
minecraft_version_range=[26.2,26.3)
neo_version=26.2.0.6-beta
neo_version_range=[26.2.0.6-beta,)
loader_version_range=[4,)
registrate_version=1.6.0

org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
