modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/tterrag1098/DummyPlayers/issues"
license = "MPLv2"

[[mods]]
modId="dummyplayers"
version="${mod_version}"
displayName="DummyPlayers"
authors="tterrag" #optional

[[dependencies.dummyplayers]] 
    modId="neoforge"
    mandatory=true 
    versionRange="[21.0.58-beta,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dummyplayers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21,1.21.1)"
    ordering="NONE"
    side="BOTH"
