modLoader = "javafml"
loaderVersion = "${loader_version_range}"
issueTrackerURL="https://github.com/LoveTropics/DummyPlayers/issues"
license = "Mozilla Public License Version 2.0"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName="DummyPlayers"
authors="tterrag"

[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
